eureka: 
  instance: 
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
redis:
  database: 0
  host: 127.0.0.1
  lettuce:
    pool:
      max-active: 8   #最大连接数据库连接数,设 0 为没有限制
      max-idle: 8     #最大等待连接中的数量,设 0 为没有限制
      max-wait: -1ms  #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
      min-idle: 0     #最小等待连接中的数量,设 0 为没有限制
    shutdown-timeout: 100ms
  password: ''
  port: 6379
spring:
  datasource:
    #type: org.apache.commons.dbcp.BasicDataSource
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://127.0.0.1:3306/method?useSSL=false&ullNamePatternMatchesAll=true&amp;serverTimezone=GMT%2b8?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
mybatis: 
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cmcc.pojo
logging: 
  level: 
    xatu.zsl: debug
    org.springfromework.web: info
    org.hibernate: error
  file: /usr/local/v2x/log/v2x-userservice.out
management: 
  endpoints: 
    web: 
      exposure: 
        include: "*"
  endpoint: 
    health: 
      show-details: always
  security:
    enabled: false

