eureka: 
  instance: 
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
redis: 
  host: 10.1.4.157
  port: 6379
  password: 123456
  maxTotal: 500
  maxIdle: 50
  maxWaitMillis: 5000
  timeOut: 5000
spring:
  datasource:
    #type: org.apache.commons.dbcp.BasicDataSource
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://10.1.4.175:3306/method?useSSL=false&ullNamePatternMatchesAll=true&amp;serverTimezone=GMT%2b8?useUnicode=true&characterEncoding=utf8
    username: root
    password: cmcc1234
mybatis: 
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cmcc.pojo
logging: 
  level: 
    xatu.zsl: debug
    org.springfromework.web: info
    org.hibernate: error
  file: /usr/local/v2x/log/v2x-userservice.out
management: 
  endpoints: 
    web: 
      exposure: 
        include: "*"
  endpoint: 
    health: 
      show-details: always
  security:
    enabled: false

