eureka: 
  instance: 
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
spring: 
  mvc: 
    view: 
      prefix: /
      suffix: .jsp
  datasource: 
    type: org.apache.commons.dbcp.BasicDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/method?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
  application: 
    name: v2x-gateway
  redis: 
    host: 127.0.0.1
    port: 6379
    password: 
mybatis: 
  mapper-locations: classpath:com/cmcc/v2x/dso/gateway/mapper/*.xml
  type-aliases-package: com.cmcc.v2x.dso.gateway.pojo
feign: 
  hystrix: 
    enabled: true
  httpclient: 
    enabled: true
  okhttp: 
    enabled: false
hystrix: 
  threadpool: 
    default: 
      coreSize: 500
      fallback: 
        enabled: true
      execution: 
        isolation: 
          thread: 
            timeoutInMilliseconds: 600000
      requestVolumeThreshold: 3
  command: 
    default: 
jwt: 
  SecretKey: test
  tokenTime: 100800
  appid : appid
logging: 
  level: 
    xatu.zsl: debug
    org.springfromework.web: info
    org.hibernate: error
  file: /usr/local/v2x/log/v2x-gateway
